baseURL = "https://gohugo.io/"
title   = "My Hugo Site"

[params]
  github = "https://github.com/bep/hugositetemplate"

# Only home for now, remove what you want.
disableKinds = [
    "taxonomy",
    "term",
    "404",
    "page",
    "robotstxt",
    "rss",
    "section",
    "sitemap",
]
